import { z } from 'zod';

// Partial update schemas (all fields optional except id)
// Note: We can't use .partial() on ZodEffects, so we create a new schema
export const updateJobPostingSchema = z.object({
  id: z.string().uuid('Invalid job ID format').optional(),
  employerId: z.string().uuid().optional(),
  title: z.string().min(1).max(200).optional(),
  description: z.string().min(10).max(5000).optional(),
  requirements: z.string().min(10).max(5000).optional(),
  responsibilities: z.string().max(5000).optional(),
  jobType: z.enum(['INTERNSHIP', 'PART_TIME', 'HOURLY_PAY', 'DAILY_PAY', 'FULL_TIME_1YEAR', 'FULL_TIME_2YEAR', 'FULL_TIME_2YEAR_PLUS']).optional(),
  country: z.string().max(100).optional(),
  province: z.string().max(100).optional(),
  district: z.string().max(100).optional(),
  city: z.string().max(100).optional(),
  isRemote: z.boolean().optional(),
  salaryMin: z.number().int().min(0).max(10000000).optional(),
  salaryMax: z.number().int().min(0).max(10000000).optional(),
  salaryType: z.enum(['MONTHLY', 'HOURLY', 'DAILY']).optional(),
  contractDuration: z.number().int().min(1).max(120).optional(),
  requiredSkills: z.any().optional(),
  experienceYears: z.number().int().min(0).max(50).optional(),
  educationLevel: z.string().max(200).optional(),
  totalPositions: z.number().int().min(1).max(1000).optional(),
  expiresAt: z.string().datetime().optional(),
}).refine((data) => {
  if (data.salaryMin && data.salaryMax && data.salaryMax < data.salaryMin) {
    return false;
  }
  return true;
}, {
  message: 'Maximum salary must be greater than or equal to minimum salary',
  path: ['salaryMax'],
});

// Individual KYC update schema - all fields optional
export const updateIndividualKYCSchema = z.object({
  fullName: z.string().min(1).max(200).optional(),
  gender: z.enum(['Male', 'Female', 'Other', 'Prefer not to say']).optional(),
  pronouns: z.string().max(50).optional(),
  dateOfBirth: z.string().datetime().optional(),
  nationalId: z.string().max(50).optional(),
  passportNumber: z.string().max(50).optional(),
  country: z.string().max(100).optional(),
  province: z.string().max(100).optional(),
  district: z.string().max(100).optional(),
  municipality: z.string().max(100).optional(),
  ward: z.string().max(10).optional(),
  street: z.string().max(200).optional(),
  city: z.string().max(100).optional(),
  email: z.string().email().optional(),
  phone: z.string().optional(),
  emergencyContact: z.string().optional(),
  highestQualification: z.string().max(200).optional(),
  fieldOfStudy: z.string().max(200).optional(),
  schoolUniversity: z.string().max(200).optional(),
  languagesKnown: z.any().optional(),
  externalCertifications: z.any().optional(),
  employmentStatus: z.string().optional(),
  experience: z.any().optional(),
  expectedSalaryMin: z.number().int().min(0).max(10000000).optional(),
  expectedSalaryMax: z.number().int().min(0).max(10000000).optional(),
  willingRelocate: z.boolean().optional(),
  technicalSkills: z.any().optional(),
  softSkills: z.any().optional(),
  physicalSkills: z.any().optional(),
  interestDomains: z.any().optional(),
  workStylePrefs: z.any().optional(),
  psychometricData: z.any().optional(),
  motivationTriggers: z.any().optional(),
  learningPrefs: z.any().optional(),
  trainingWillingness: z.number().int().min(1).max(5).optional(),
  availableHoursWeek: z.number().int().min(1).max(168).optional(),
  careerGoals: z.string().max(5000).optional(),
  areasImprovement: z.any().optional(),
  digitalLiteracy: z.string().optional(),
  preferredIndustry: z.string().max(200).optional(),
  references: z.any().optional(),
  portfolioUrls: z.any().optional(),
  videoIntroUrl: z.string().url().optional(),
  socialMediaUrls: z.any().optional(),
  profilePhotoUrl: z.string().url().optional(),
  consentGiven: z.boolean().optional(),
});

export const updateIndustrialKYCSchema = z.object({
  id: z.string().uuid().optional(),
  companyName: z.string().min(1).max(200).optional(),
  companyEmail: z.string().email().optional(),
  companyPhone: z.string().optional(),
  registrationNumber: z.string().max(100).optional(),
  yearsInBusiness: z.number().int().min(0).max(200).optional(),
  companySize: z.string().optional(),
  industrySector: z.string().max(200).optional(),
  country: z.string().max(100).optional(),
  province: z.string().max(100).optional(),
  district: z.string().max(100).optional(),
  municipality: z.string().max(100).optional(),
  ward: z.string().max(10).optional(),
  street: z.string().max(200).optional(),
  contactPersonName: z.string().max(100).optional(),
  contactPersonDesignation: z.string().max(100).optional(),
  contactPersonPhone: z.string().optional(),
});
